@CRUD_HostAddress = http://localhost:5130

GET http://localhost:5130/assets?search=DELL&status=Assigned&category=Monitors&pageNumber=1&pageSize=1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjU3NDUxMzBjLTE4NzQtZjExMS1hZmM2LTRjNzk2ZWNjZWY0MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IjEiLCJleHAiOjE3ODI3ODI0OTMsImlzcyI6Ik15QXBpIiwiYXVkIjoiTXlBcGlVc2VycyJ9.2c5N8aa4fS4HBmaO88IWU4mfHFwgHTQsuw0v9t5m5lg


### https
GET https://localhost:7117/assets?search=DELL&pageNumber=1&pageSize=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjU3NDUxMzBjLTE4NzQtZjExMS1hZmM2LTRjNzk2ZWNjZWY0MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IjEiLCJleHAiOjE3ODI3ODI0OTMsImlzcyI6Ik15QXBpIiwiYXVkIjoiTXlBcGlVc2VycyJ9.2c5N8aa4fS4HBmaO88IWU4mfHFwgHTQsuw0v9t5m5lg

###

POST {{CRUD_HostAddress}}/assets/assignment
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "assetId": 1,
  "employeeId": 2
}
